const DesignWorks = [
    {
        thumbnail: "/project-files/design/br-kiosk/cover.png",
        name: "Baskin Robbins Kiosk",
        desc: ['05/03/2023', 'Trying to design an ordering kiosk for Baskin Robbins'],
        source: "https://player.vimeo.com/video/823520004?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479",
        problemStatement: 'My goal for this project was to design a kiosk that could streeamline the ordering process at Baskin Robbins. Information densitiy anjd organization were key in this project, so despite all of the technical UI/UX problems a question I had to ask myself was "how do I compress this large catalogue of info into degestible and traversible content?"',
        solution: "The first step was to do a heuristic evalutation on other existing kiosks. After looking at what worked and what didn't, I created a document that would organize all of the information I'd need for the kiosk and specific device requirements.",
        process: ["/project-files/design/br-kiosk/process.png", "Freehand sketching some measurements for kiosk dimensions and the size relation to actual users"],
        conclusion: "After tons of trial and error, crafting a user flow diagram, and experimenting with screen sizes the final result was a simple kiosk that mainly grouped similar items into larger, easier-to-manage categories.",
        toolsUsed: ['Figma', 'Clip Studio Paint', 'Adobe After Effects'],
        isEmbed: true,
        img: 'link to img',
        caseStudy: "/project-files/design/br-kiosk/br-process-doc.pdf",
        files: "/project-files/design/br-kiosk/source.zip",
    },
    {
        thumbnail: "/project-files/design/ddl/cover.png",
        name: "Digital Driver's License",
        desc: ['02/23/2023', 'A project in which I attempt to digitize a driver\'s license'],
        source: "https://player.vimeo.com/video/801842633?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479",
        problemStatement: "For this project I looked at physical driver's licenses and thought about their pain points. They're jam packed with information, harming their readability and physical; meaning that if you lose them, it can be a hassle to get a replacement. How can the information on the license be made to-the-point and readable?",
        solution: "I was heavily inspired by digital finace apps like Cashapp and Venmo, and employee cards that're sometimes used in certain workplaces. Both of those things have a way of organizing information into manageable chunks that I thought would be useful for the solution to my design problem.",
        process: ["/project-files/design/ddl/process.png", "Sketches of multiple styles/iterations of the license I had in my head"],
        conclusion: "By prioritizing important information and then organizing it, I managed to create a proof of concept digital driver's license that tries to make using a license seamless and cool for the user.",
        toolsUsed: ['Figma', 'Adobe After Effects'],
        isEmbed: true,
        img: 'link to img',
        caseStudy: "/project-files/design/ddl/ddl-process-doc.pdf",
        files: "/project-files/design/ddl/source.zip",
    },
    {
        thumbnail: "/project-files/design/encryption/cover.png",
        name: "Encryption",
        desc: ['09/22/2022', 'A word animation that depicts how I see the word "Encryption"(or rather I saw it at the time of making this)'],
        source: "https://player.vimeo.com/video/901654454?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479",
        problemStatement: "I wanted to make a word animation based on the word 'encryption'. A lot of the problem with this is figuring out how to depict the word's meaning without being too on-the-nose.",
        solution: "I started out by brainstorming ideas and then deciding on the vibe I wanted to go for; I had already been working on a language for some time before this project so I thought that I'd incorporate it as well.",
        process: ["/project-files/design/encryption/process.png", "formally creating glyphs for the alphabet of my language 'Gdnsua' and making a number system for funzies"],
        conclusion: "After everything's said and done, the final result was an animation that I think captured the cryptic feeling of the word encryption while portraying some cool techno vibes as well. This project was much more intuition-driven than my others, so there really isn't a formal case study.",
        toolsUsed: ['Figma', 'Adobe After Effects'],
        isEmbed: true,
        img: 'link to img',
        caseStudy: "https://www.figma.com/file/OL3YIBvPr4LVvIfrabPmeX/WIP_enc?type=design&mode=design&t=VyvjmLR07DVwzl9m-1",
        files: "/project-files/design/encryption/source.zip",
    },
    {
        thumbnail: "/project-files/design/mandala/cover.png",
        name: "Mandala Project",
        desc: ['02/17/2022', 'Using Adobe After Effects to make some cool mandala-themed motion graphics stuff'],
        source: "https://player.vimeo.com/video/903000582?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479",
        problemStatement: "I wanted to create a motion graphics piece that represented who I was as a person/designer in the year of 2022. How could I achieve this while sticking to a mandala motif?",
        solution: "I took inspiration from various sources of media like manga, commercials, vector graphic art, etc. I really wanted to lead the viewer through an experience instead of showing them cool things, so I used that desire as a base for my transitions and poster shots.",
        process: ["/project-files/design/mandala/process.png", "Some early concept sketches of the project and ideas that I wanted to incorporate"],
        conclusion: "The end result is something that I'm proud of to this day. It isn't perfect by any means, and can definitely benefit from improved timing and some revisions, but it's a piece I'm glad I made nonetheless.",
        toolsUsed: ['Adobe After Effects', 'Music: Chronograph from Clockwork Planet'],
        isEmbed: true,
        img: 'link to img',
        caseStudy: "/project-files/design/mandala/mandala-process-doc.pdf",
        files: "/project-files/design/mandala/source.zip",
    },
    {
        thumbnail: "/project-files/design/surreal-world/cover.png",
        name: "Surreal World",
        desc: ['04/06/2022', 'A project in which I lead the viewer through a fantasy world.'],
        source: "https://player.vimeo.com/video/903014835?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479",
        problemStatement: "I wanted to immerse the viewer into a fantasy setting that would change over time. How did I go about doing this while keeping the style and overall piece together?",
        solution: "I decided to simplify the style and use vector graphics and basic shapes across scenes to mae sure that each one retained the same style. I als use camera movements to guide the viewer through the scenes in ways that I thought would be interesting.",
        process: ["/project-files/design/surreal-world/process.png", "A page from my pitch deck showcasing the ideas I'd be going for."],
        conclusion: "All of that lead to a piece that guides the viewer through a fantasy world of many scenes.",
        toolsUsed: ['Adobe After Effects', 'Adobe Illustrator', 'Music: Hanging Garden by Sakuzyo'],
        isEmbed: true,
        img: 'link to img',
        caseStudy: "/project-files/design/surreal-world/surreal-world-process-doc.pdf",
        files: "/project-files/design/surreal-world/source.aep",
    },
]

export default DesignWorks