const ImageSources = [
    {
        url: '/images/illust/1_t.png',
        illust: '/images/illust/1.png',
        title: 'SPARK',
        desc: 'I wanted to experiment more with foreshortening and VFX in this piece, so I chose a pretty complicated hand position and tried to create a bright composition from that',
        tags: ['scene'],
    },
    {
        url: '/images/illust/2_t.png',
        illust: '/images/illust/2.png',
        title: 'ARLHEMI',
        desc: 'A character designed and based off of an old database of game characters I made a while back. I wanted to go for a mix of Akihiko Yoshida and official Square Enix character design style',
        tags: ['character', 'design'],
    },
    {
        url: '/images/illust/3_t.png',
        illust: '/images/illust/3.png',
        title: 'MATHOS',
        desc: 'A character designed and based off of an old database of game characters I made a while back. I wanted to try my best in terms of conveying a paladin vibe',
        tags: ['character', 'design'],
    },
    {
        url: '/images/illust/4_t.png',
        illust: '/images/illust/4.png',
        title: 'FREYA',
        desc: 'This is an original character that I designed. I wanted the design of the overall illustration to look like those character unlocked screens in gacha games',
        tags: ['character', 'design'],
    },
    {
        url: '/images/illust/5_t.png',
        illust: '/images/illust/5.png',
        title: 'KOHARU YAGIMOTO',
        desc: 'An original character I made based off of some online reference images. I wanted to try and use a new method of drawing water that involved using a combination of brushes, gradients and layering',
        tags: ['character', 'design'],
    },
    {
        url: '/images/illust/6_t.png',
        illust: '/images/illust/6.png',
        title: 'MATHILDA',
        desc: 'Original character I designed. I wanted the composition for this character tobe a bit different from my other works, so I tried to tilt the image, make the light source come from below, and give the subject a more dynamic standing pose',
        tags: ['character'],
    },
    {
        url: '/images/illust/7_t.png',
        illust: '/images/illust/7.png',
        title: 'NEW YEAR 2024',
        desc: 'A postcard-esque illustration I made to sort of bid farewell to 2023. The end of that year was a mixture of good and bad feelings, but I wanted to focus on how to move forward with the good while forgetting the bad. This image is what came to mind when thinking about drawing those feelings',
        tags: ['scene', 'misc', 'design'],
    },
    {
        url: '/images/illust/8_t.png',
        illust: '/images/illust/8.png',
        title: 'YEAR OF THE DRAGON',
        desc: 'A poster image I made to celebrate the new year. I don\'t really participate in a lot of social media art challenges/trends, but I do like how most artists use the Chinese zodiac as inspiration for what to draw during a given new year. I did the same and this is the result. Side note: I always pondered about how dragon-humanoid characters would look realistically and imagined them being more harpy-like than humanoid',
        tags: ['scene', 'design'],
    },
    {
        url: '/images/illust/9_t.png',
        illust: '/images/illust/9.png',
        title: 'THUMBTACK KNIGHT',
        desc: 'One of a series of characters design based off of ordinary objects and Pinterest pin ideas. If I could redesign the character I\'d probably make the sword longer and incorporate more spikes into the armor to really sell the thumbtack design',
        tags: ['character', 'design'],
    },
    {
        url: '/images/illust/10_t.png',
        illust: '/images/illust/10.png',
        title: 'WATER VASE GUNNER',
        desc: 'One of a series of characters design based off of ordinary objects and Pinterest pin ideas. I saw a pin of this weird looking water vase and thought that it\'d be cool as a gun',
        tags: ['character', 'design'],
    },
    {
        url: '/images/illust/11_t.png',
        illust: '/images/illust/11.png',
        title: 'VINE DICE TRICKSTER',
        desc: 'One of a series of characters design based off of ordinary objects and Pinterest pin ideas. For this character I got inspired by this awesome pin of a cherry on pinterest. It was basically a cherry with dice replacing the fruit',
        tags: ['character', 'design'],
    },
    {
        url: '/images/illust/12_t.png',
        illust: '/images/illust/12.png',
        title: 'TANGERINE GLOBE MAGE',
        desc: 'One of a series of characters design based off of ordinary objects and Pinterest pin ideas. I saw a tangerine with it\'s skin peeled in a way that made the fruit look like a globe and then thought that that\'d be a pretty cool mage staff',
        tags: ['character', 'design'],
    },
    {
        url: '/images/illust/13_t.png',
        illust: '/images/illust/13.png',
        title: 'WATERPOT FIEND',
        desc: 'One of a series of characters design based off of ordinary objects and Pinterest pin ideas. This guy is based off of a cool clay pot I saw on the internet while casually googling stuff',
        tags: ['character', 'design'],
    },
    {
        url: '/images/illust/14_t.png',
        illust: '/images/illust/14.png',
        title: 'SPEDOMETER GIRL',
        desc: 'One of a series of characters design based off of ordinary objects and Pinterest pin ideas. After realizing that I don\'t draw a lot of vehicles, I went to Pinterest and looked for some cool vehicles to draw. I saw this cool looking motorbike and was set. This piece revealed to me that I can sort of draw anything as long as I have a reference, focus, and remember to observe what I\'m drawing well',
        tags: ['character', 'design'],
    },
    {
        url: '/images/illust/15_t.png',
        illust: '/images/illust/15.png',
        title: 'ARCANE GRAPHITE SKETCHER',
        desc: 'One of a series of characters design based off of ordinary objects and Pinterest pin ideas. I was picking random pins from a Pinterest board full of everyday house objects and got a pencil',
        tags: ['character', 'design'],
    },
    {
        url: '/images/illust/16_t.png',
        illust: '/images/illust/16.png',
        title: 'MECHA PENCIL SPEAR BEARER',
        desc: 'One of a series of characters design based off of ordinary objects and Pinterest pin ideas. I thought that it would be cool to design a spear user that could electrify theor weapon with controls on the spear. That, combined with an image of a mechanical pencil that I found on Pinterest, gave birth to this character',
        tags: ['character', 'design'],
    },
    {
        url: '/images/illust/17_t.png',
        illust: '/images/illust/17.png',
        title: 'CHLOE BLOODGARDEN',
        desc: 'A redesign of an edgy grim reaper character I made a some years back. I wanted to experiment with more dynamic composition and shapes in this piece as well',
        tags: ['character', 'design'],
    },
    {
        url: '/images/illust/18_t.png',
        illust: '/images/illust/18.png',
        title: 'DESIGN: RED',
        desc: 'After seeing a bunch of editorial and graphic designs in my causal internet surfing, I felt compelled to try mixing some of what I saw with character-based illustration',
        tags: ['design'],
    },
    {
        url: '/images/illust/19_t.png',
        illust: '/images/illust/19.png',
        title: 'FIRST TIME',
        desc: 'A redraw of my first digital art piece ever drawn from about 5 years ago',
        tags: ['design'],
    },
    {
        url: '/images/illust/20_t.png',
        illust: '/images/illust/20.png',
        title: 'INNER MAKIMA',
        desc: 'A short story cover I was commissioned to draw. The client want more dynamic lighting with a slight painterly feel, so I did my best to fit their needs',
        tags: ['design', 'scene'],
    },
    {
        url: '/images/illust/21_t.png',
        illust: '/images/illust/21.png',
        title: 'COUCH',
        desc: 'Back in my monochrome art phase I was obsessed with copying some of my favorite mangaka and making detail heavy scenes with as many pen and ink skills as possible. This is one of those pieces',
        tags: ['character', 'scene'],
    },
    {
        url: '/images/illust/22_t.png',
        illust: '/images/illust/22.png',
        title: 'JAMES CAGE BLUE',
        desc: 'I was commissioned to draw a character for a meme page on instagram in a Jojo style',
        tags: ['character'],
    },
    {
        url: '/images/illust/23_t.png',
        illust: '/images/illust/23.png',
        title: 'MEMORIES OF SUMMER',
        desc: 'Album cover for an album I was making during the summer of 2023. I completed the album and made several variations of the cover to fit the vibe of each song in it, but liked this one the most because of the sepia color',
        tags: ['design'],
    },
    {
        url: '/images/illust/24_t.png',
        illust: '/images/illust/24.png',
        title: 'COLOR TESTING',
        desc: 'This was me experimenting with different ways of shading colored illustrations. I previously used to have a base and shade color for each color in a given illustration, but that made the coloring process take a long time and get boring to me. I wanted to see if there was a way to use one shade on a colored Illustration and still make the lighting presentable',
        tags: ['misc'],
    },
    {
        url: '/images/illust/25_t.png',
        illust: '/images/illust/25.png',
        title: 'MIND\'S EYE',
        desc: 'An original character I made a while ago. I wanted an intense and sort of grungy feel to be conveyed through this piece',
        tags: ['misc'],
    },
    {
        url: '/images/illust/26_t.png',
        illust: '/images/illust/26.png',
        title: 'PLAGUE',
        desc: 'An original character I designed some years back. She\'s supposed to be one of a series of villain characters, but I never got around to creating the others',
        tags: ['character'],
    },
    {
        url: '/images/illust/27_t.png',
        illust: '/images/illust/27.png',
        title: 'DUOMO DI MILANO',
        desc: 'Cover art for a final project me and a partner did in an interior design class. The background image credit: https://unsplash.com/ja/@manuelweber',
        tags: ['design'],
    },
];

export default ImageSources