const MusicSources = [
    {
        thumbnail: "/music/thumbnails/mos.png",
        trackTitle: "夜明け feat.Mai",
        trackDesc: "Dawn. The 2nd track from my 'Memories of Summer' album. I used vocal a synthesizing software called 'synthV' for the vocals",
        track: "/music/夜明け.mp3",
        flavor: "darkBlue",
        date: "September 2023",
        tags: ['Misc', 'JPOP'],
    },
    {
        thumbnail: "/music/thumbnails/mos.png",
        trackTitle: "突風 feat.Mai",
        trackDesc: "Gust. The 4th track from my 'Memories of Summer' album. I used vocal a synthesizing software called 'synthV' for the vocals",
        track: "/music/突風.mp3",
        flavor: "darkRed",
        date: "September 2023",
        tags: ['Misc', 'JROCK'],
    },
    {
        thumbnail: "/music/thumbnails/mos.png",
        trackTitle: "黄昏 feat.Mai",
        trackDesc: "Twilight. The 6th track from my 'Memories of Summer' album. I used vocal a synthesizing software called 'synthV' for the vocals",
        track: "/music/黄昏.mp3",
        flavor: "darkRed",
        date: "September 2023",
        tags: ['Misc', 'JROCK'],
    },
    {
        thumbnail: "/music/thumbnails/mow.png",
        trackTitle: "Wave Macy",
        trackDesc: "The 9th track from my 'Myth of Water' album",
        track: "/music/wave-macy_nrm_SFX.mp3",
        flavor: "darkRed",
        date: "January 2023",
        tags: ['Misc', 'JROCK'],
    },
    {
        thumbnail: "/music/thumbnails/mow.png",
        trackTitle: "Wave Macy Loon",
        trackDesc: "The 4th track from my 'Myth of Water' album",
        track: "/music/wave-macy_loony_SFX.mp3",
        flavor: "darkRed",
        date: "December 2022",
        tags: ['Misc', 'JROCK'],
    },
    {
        thumbnail: "/music/thumbnails/e.png",
        trackTitle: "Wandering",
        trackDesc: "BGM from my Encryptopedia game project. This is the free roaming music",
        track: "/music/wandering.wav",
        flavor: "black",
        date: "May 2022",
        tags: ['Misc'],
    },
    {
        thumbnail: "/music/thumbnails/mos.png",
        trackTitle: "散歩",
        trackDesc: "Walking. The 3rd track from my 'Memories of Summer' album",
        track: "/music/walking.mp3",
        flavor: "blue",
        date: "September 2023",
        tags: ['JPOP'],
    },
    {
        thumbnail: "/music/thumbnails/mow.png",
        trackTitle: "Tropical",
        trackDesc: "The 3rd track from my 'Myth of Water' album",
        track: "/music/Tropical_Complete_SFX.mp3",
        flavor: "blue",
        date: "December 2022",
        tags: ['JPOP'],
    },
    {
        thumbnail: "/music/thumbnails/mow.png",
        trackTitle: "Swaying Fin",
        trackDesc: "The 6th track from my 'Myth of Water' album",
        track: "/music/swaying_fin.mp3",
        flavor: "cyan",
        date: "December 2022",
        tags: ['JPOP', 'Jazzy', 'Misc'],
    },
    {
        thumbnail: "/music/thumbnails/mow.png",
        trackTitle: "Storm Dream",
        trackDesc: "The 5th track from my 'Myth of Water' album",
        track: "/music/storm_dream.mp3",
        flavor: "blue",
        date: "December 2022",
        tags: ['JPOP'],
    },
    {
        thumbnail: "/music/thumbnails/mos.png",
        trackTitle: "道",
        trackDesc: "Road. The 9th and final offical track from my 'Memories of Summer' album",
        track: "/music/road.wav",
        flavor: "darkBlue",
        date: "September 2023",
        tags: ['JPOP', 'Misc'],
    },
    {
        thumbnail: "/music/thumbnails/mow.png",
        trackTitle: "Ride The Blue",
        trackDesc: "The 8th track from my 'Myth of Water' album. I tried experimenting with different audio tools and sound samples",
        track: "/music/ride-the-blue.mp3",
        flavor: "blue",
        date: "January 2023",
        tags: ['JPOP'],
    },
    {
        thumbnail: "/music/thumbnails/e.png",
        trackTitle: "Pause Menu",
        trackDesc: "BGM from my Encryptopedia game project. This is the pause menu music",
        track: "/music/pause_menu.wav",
        flavor: "black",
        date: "May 2023",
        tags: ['Misc',],
    },
    {
        thumbnail: "/music/thumbnails/mos.png",
        trackTitle: "懐かしいオレンジ",
        trackDesc: "Nostalgic Orange. The 5th track from my 'Memories of Summer' album",
        track: "/music/orange-nostalgia.mp3",
        flavor: "darkBlue",
        date: "September 2023",
        tags: ['Misc', 'JPOP'],
    },
    {
        thumbnail: "/music/thumbnails/mow.png",
        trackTitle: "Myth",
        trackDesc: "The first track from my 'Myth of Water' album.",
        track: "/music/Myth_SFX.mp3",
        flavor: "Purple",
        date: "November 2022",
        tags: ['Misc', 'Jazzy'],
    },
    {
        thumbnail: "/music/thumbnails/mos.png",
        trackTitle: "旅程",
        trackDesc: "Itinerary. The 8th track from my 'Memories of Summer' album",
        track: "/music/itinerary.mp3",
        flavor: "black",
        date: "September 2023",
        tags: ['Misc'],
    },
    {
        thumbnail: "/music/thumbnails/mos.png",
        trackTitle: "黄昏(Instrumental)",
        trackDesc: "Instrumental version of Twilight",
        track: "/music/instrumental-twilight.wav",
        flavor: "darkRed",
        date: "September 2023",
        tags: ['Misc', 'JROCK'],
    },
    {
        thumbnail: "/music/thumbnails/mos.png",
        trackTitle: "突風(Instrumental)",
        trackDesc: "Instrumental version of Gust",
        track: "/music/instrumental-gust.wav",
        flavor: "darkRed",
        date: "September 2023",
        tags: ['Misc', 'JROCK'],
    },
    {
        thumbnail: "/music/thumbnails/mos.png",
        trackTitle: "夜明け(Instrumental)",
        trackDesc: "Instrumental version of Dawn",
        track: "/music/instrumental-dawn.wav",
        flavor: "darkBlue",
        date: "September 2023",
        tags: ['Misc', 'JPOP'],
    },
    {
        thumbnail: "/music/thumbnails/mos.png",
        trackTitle: "草の葉",
        trackDesc: "Blade of Grass. The 7th track in my 'Memories of Summer' album",
        track: "/music/grassblade.mp3",
        flavor: "black",
        date: "September 2023",
        tags: ['Misc'],
    },
    {
        thumbnail: "/music/thumbnails/e.png",
        trackTitle: "Decrypt",
        trackDesc: "BGM from my Encryptopedia game project. This track plays when the user 'decrypts' ciphers",
        track: "/music/decrypt.wav",
        flavor: "black",
        date: "May 2023",
        tags: ['Misc'],
    },
    {
        thumbnail: "/music/thumbnails/mos.png",
        trackTitle: "横風",
        trackDesc: "Crosswind. The first track from my 'Memories of Summer' album. I wanted it to set the tone for all of the other tracks in terms of instrumentation",
        track: "/music/crosswind.wav",
        flavor: "darkBlue",
        date: "September 2023",
        tags: ['Misc', 'JPOP'],
    },
    {
        thumbnail: "/music/thumbnails/mow.png",
        trackTitle: "Chrono Aquaria",
        trackDesc: "The last track from my 'Myth of Water' album. I wanted to try and make a song that could appear in an RPG map",
        track: "/music/chrono-aquaria.mp3",
        flavor: "black",
        date: "January 2023",
        tags: ['Misc'],
    },
    {
        thumbnail: "/music/thumbnails/mow.png",
        trackTitle: "Bare Tide",
        trackDesc: "The second track from my 'Myth of Water' album. I was still getting used to making music with Online Sequencer",
        track: "/music/bare-tide-SFX.mp3",
        flavor: "black",
        date: "December 2022",
        tags: ['Misc'],
    },
    {
        thumbnail: "/music/thumbnails/leyline.png",
        trackTitle: "Leyline Crossing",
        trackDesc: "A song I made heavily inspired by 削除(Sakuzyo). I really wanted the song to have a sort of 'free' feeling to it",
        track: "/music/leyline_crossing.mp3",
        flavor: "darkRed",
        date: "January 2023",
        tags: ['Misc', 'JROCK'],
    },
    {
        thumbnail: "/music/thumbnails/rock.png",
        trackTitle: "Rock: B",
        trackDesc: "I was going for a slightly contrasting rock feel compared to Roll: A and experimenting with drums more in this song",
        track: "/music/rock-b.mp3",
        flavor: "red",
        date: "July 2023",
        tags: ['JROCK'],
    },
    {
        thumbnail: "/music/thumbnails/roll.png",
        trackTitle: "Roll: A",
        trackDesc: "My attempt at a JROCK style instrumental song. I wanted to incorporate more guitar in this song compared to my previous works",
        track: "/music/roll-a.wav",
        flavor: "red",
        date: "January 2023",
        tags: ['JROCK'],
    },
]

export default MusicSources